### ISSUE TITLE
Converting sending functions in lua

### ISSUE THREAD

**Issue by PMassicotte** [jalvesaq/tmp-R-Nvim#1]
I have started to implement the sending code functions:

- https://github.com/PMassicotte/tmp-R-Nvim/blob/send-functions-lua/lua/r/sendfn.lua
- https://github.com/PMassicotte/tmp-R-Nvim/blob/send-functions-lua/lua/r/cursor_nav.lua

At this time, I am using `RSourceLines` to send the captured code to R.

https://github.com/PMassicotte/tmp-R-Nvim/blob/e6ff26b577434c67695ab7441e903a53f1fb9586/R/start_r.vim#L1433-L1437

Do you think I am on the right path?

**Comment by PMassicotte** [comment]
Sounds perfect, I will make change to suggestions and implement other sending functions.

**Comment by jalvesaq** [comment]
Could you do the pull request immediately? We can fix any bugs later. I'm converting `R/nvimcom.vim`, `R/start_nrs.vim`, and the StartR function, and it is becoming increasingly difficult to deal with the Vim code and their global variables from Lua.

**Comment by jalvesaq** [comment]
I have to stop working on this for a few days again. What is already converted to Lua should work with few bugs. VimScript code no longer works because the configuration is now exclusively stored in the config table of `lua/r/config.lua` and in local variables at some other modules. Consequently, any Lua code depending on old VimScript also will not work.

`cmp-nvim-r` no longer works with `R-Nvim` because it depends on the `g:rplugin` dictionary, which is no longer available.

Regarding the organization, I think it could be named "R-Nvim", and, as in many other Github organizations, its main project would have the same name: "R-Nvim". Another project would be "cmp-r".

**Comment by PMassicotte** [comment]
I like the organization idea!

I am teaching today and tomorrow, so I can not work on it, but I will pull changes and see what I can do next.

**Comment by jalvesaq** [comment]
I still pushed some changes, but now I really have to stop until Saturday.

We will start the organization when the conversion to Lua is finished.

**Comment by jalvesaq** [comment]
I changed the code to:

```lua
    if vim.fn.isdirectory(dir_path) ~= 1 then
        local status, err = pcall(function()
            vim.fn.mkdir(dir_path, "p")
        end)
        -- Check if pcall caught an error
        if not status then
            -- Log or handle the error as needed
            print("Error creating directory: " .. err)
            -- Optionally, return false to indicate failure
            return false
        end
    end
```

But the error remains. Then, I changed it to:

```lua
    if vim.fn.isdirectory(dir_path) ~= 1 then
        if vim.fn.mkdir(dir_path, "p") ~= 1 then
            -- Return false to indicate failure
            print("Error creating directory")
            return false
        end
    end
    -- Return true to indicate success
    return true
```

But the error still remains.

**Comment by jalvesaq** [comment]
I'm sorry, I commented on the wrong issue.

**Comment by PMassicotte** [comment]
btw, almost done with all the sending functions. PR will come this weekend.

**Comment by jalvesaq** [comment]
Great news!

**Comment by jalvesaq** [comment]
I will convert the remaining functions from `R/common_global.vim` and delete then it.

**Comment by PMassicotte** [comment]
Perfect!

**Comment by jalvesaq** [comment]
I converted to Lua and deleted some functions from `R/start_r.vim`.

**Comment by PMassicotte** [comment]
Should we create a milestone with a list of things to do?

**Comment by jalvesaq** [comment]
It's a good idea. Some items for the list:

- Convert VimScript to Lua.
- Replace as much `vim.fn` functions with `vim.api` or standard Lua alternatives. Examples:

```
    vim.fn.getline            = vim.api.nvim_buf_get_lines
    vim.fn.setlines           = vim.api.nvim_buf_set_lines
    vim.fn.substitute         = string.gsub, vm.regex,
    vim.fn.system             = vim.system
    vim.fn.map, vim.fn.filter = vim.split + loop for
    vim.fn.timer_start        = vim.schedule
```
- Try all features and fix the bugs.

At this point, `tmp-R-Nvim` code should be ready to be copied to `R-Nvim/R-Nvim`. It would have no advantage over `Nvim-R` but would be ready for further development and integration with other Neovim plugins.

**Comment by PMassicotte** [comment]
I can do the replace and will make a PR soon.

**Comment by jalvesaq** [comment]
Thanks!

**Comment by PMassicotte** [comment]
I just did one file so far (at a conference until tomorrow). I can PR it now if you want.

**Comment by jalvesaq** [comment]
Yes, please, do the PR... and enjoy your conference!

**Comment by jalvesaq** [comment]
All functions are converted to Lua, although some of them don't work yet.

**Comment by jalvesaq** [comment]
Only syntax scripts are still in VimScript, but I don't know if there is any advantage to convert them to Lua.
