### ISSUE TITLE
Organization and project names

### ISSUE THREAD

**Issue by jalvesaq** [jalvesaq/tmp-R-Nvim#14]
I started this repository as `tmp-R-Nvim`, but @she3o used `R.nvim` in the CONTRIBUTING.md document. So, we have at least two options. `R-Nvim` (closer to `Nvim-R`) and `R.nvim` (resembling the names of many other Neovim plugins). Since we are refactoring `Nvim-R`, I think there is no reason to choose a name similar to the old one, and `R.nvim` is easier to type...

**Comment by PMassicotte** [comment]
I am good for R.nvim.

**Comment by jalvesaq** [comment]
The names were updated in the last commit. So, closing this issue...
