### ISSUE TITLE
R, hooks; scripts, nvimcom

### ISSUE THREAD

**Issue by jalvesaq** [jalvesaq/tmp-R-Nvim#29]
I'm thinking about renaming some directories and moving some files from one directory to another:

Move `nvimcom` to the root of `R.nvim`, so, we have to type less when accessing it.

Rename `R` as `scripts` as common in many other plugins.

Move `hooks/pre_comit` to `scripts`.

Delete `hooks`.

What do you think, @PMassicotte and @she3o? Any objections or better ideas?

**Comment by PMassicotte** [comment]
Sounds perfectly fine with me.
